CXX= c++ -std=c++20

pluck:
	@$(CXX) t_pluck.cpp
	@./a.out

noise:
	@$(CXX) t_noise.cpp
	@./a.out

onepole:
	@$(CXX) t_onepole.cpp
	@./a.out

mean:
	@$(CXX) t_mean.cpp
	@./a.out

slew:
	@$(CXX) t_slew.cpp
	@./a.out
